// Catches truncation of the upper 256 bits when folding a 64-byte memory word.
{
    mstore(0, 0x0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40)
    sstore(0, keccak256(0, 0x40))
}
// ----
// step: loadResolver
//
// {
//     {
//         let _1 := 0x0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40
//         let _2 := 0
//         mstore(_2, _1)
//         sstore(_2, 82910411434043509702368619386649266079818424832347194105815380559256974697969)
//     }
// }
